import 'package:flutter_application_1/user.dart';

final List<User> users = [
  User(
    imageURL: 'images/1.jpg',
    name: 'Abuubakar Ciise',
    role: '',
    message: "Busy",
    time: "4:38 PM",
    subtitle: "ME",
    callTime: "Yesterday, 10:56 PM", 
    isOutgoingCall: true,
  ),
  User(
    imageURL: 'images/2.png',
    name: 'Adnaan Hassan',
    role: 'Mobile Developer',
    message: "at the gym",
    time: "4:38 PM",
    subtitle: "ME",
    callTime: "Yesterday, 11:50 PM", 
    isOutgoingCall: false,
  ),
  User(
    imageURL: 'images/3.png',
    name: 'C.Laahi Diiriye',
    role: 'Full Stack Developer',
    message: "Sleeping",
    time: "4:38 PM",
    subtitle: "ME",
    callTime: "Yesterday, 8:15 AM", 
    isOutgoingCall: true,
  ),
  User(
    imageURL: 'images/4.jpeg',
    name: 'Ciise Ali',
    role: 'UI/UX Designer',
    message: "Working on a project",
    time: "9:00 PM",
    subtitle: "ME",
    callTime: "Yesterday, 9:30 PM", 
    isOutgoingCall: false,
  ),
  User(
    imageURL: 'images/5.jpeg',
    name: 'Faarax Maxamed',
    role: 'Backend Developer',
    message: "Coding all day",
    time: "10:15 AM",
    subtitle: "ME",
    callTime: "Today, 10:30 AM", 
    isOutgoingCall: true,
  ),
  User(
    imageURL: 'images/6.jpeg',
    name: 'Jaamac Cumar',
    role: 'Product Manager',
    message: "Reviewing documents",
    time: "2:45 PM",
    subtitle: "ME",
    callTime: "Today, 3:00 PM", 
    isOutgoingCall: false,
  ),
  User(
    imageURL: 'images/7.jpeg',
    name: 'Axmed Maxamed',
    role: 'QA Engineer',
    message: "Testing features",
    time: "5:30 PM",
    subtitle: "ME",
    callTime: "Today, 6:00 PM", 
    isOutgoingCall: true,
  ),
  User(
    imageURL: 'images/8.png',
    name: 'Saalax Yuusuf',
    role: 'Marketing Specialist',
    message: "Planning campaigns",
    time: "8:45 AM",
    subtitle: "ME",
    callTime: "Yesterday, 9:15 AM", 
    isOutgoingCall: false,
  ),
  User(
    imageURL: 'images/9.png',
    name: 'Mahad Cabdi',
    role: 'Data Analyst',
    message: "Crunching numbers",
    time: "11:15 AM",
    subtitle: "ME",
    callTime: "Today, 11:45 AM", 
    isOutgoingCall: true,
  ),
  User(
    imageURL: 'images/10.jpeg',
    name: 'Hanad Maxamed',
    role: 'Graphic Designer',
    message: "Creating new designs",
    time: "1:25 PM",
    subtitle: "ME",
    callTime: "Today, 1:55 PM", 
    isOutgoingCall: false,
  ),
];


final List<Data> data = [
  Data(imageURL: 'images/1.jpg', name: 'Abuubakar Ciise', subtitle: "ME"),
  Data(imageURL: 'images/2.png', name: 'Adnaan Hassan', subtitle: "ME"),
  Data(imageURL: 'images/3.png', name: 'C.Laahi Diiriye', subtitle: "ME"),
];
